# Generated by Django 6.0.3 on 2026-03-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('priority', models.CharField(choices=[('Низкий', 'Low'), ('Средний', 'Medium'), ('Высокий', 'High')], max_length=15)),
                ('status', models.CharField(choices=[('Новый', 'New'), ('В работе', 'In Work'), ('Завершен', 'Completed'), ('Отменен', 'Cancelled')], default='Новый', max_length=15)),
                ('deadline', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
            ],
        ),
    ]
